name: Build and Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          app/build/outputs/apk/debug/app-debug.apk
        generate_release_notes: true
        name: VoiceMesh ${{ github.ref_name }}
        body: |
          ## VoiceMesh Android App Release
          
          📱 **Download and install the APK below**
          
          ### Features:
          - 🎤 Voice recording and playback
          - 📡 Bluetooth mesh networking  
          - 🔒 Ephemeral messaging (auto-delete)
          - 👥 Peer-to-peer communication
          
          ### Installation:
          1. Download `app-debug.apk`
          2. Enable "Unknown Sources" in Android settings
          3. Install the APK
          4. Grant microphone and Bluetooth permissions
          
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}